version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Use uv to install dependencies from pyproject.toml
python:
  install:
    - method: uv
      path: .
      extra_requirements:
        - doc
