[build-system]
build-backend = "hatchling.build"
requires = [ "hatch-vcs", "hatchling" ]

[project]
name = "pydeseq2"
description = "A python implementation of DESeq2."
readme = "README.md"
license = { file = "LICENSE" }
maintainers = [
  { name = "Boris Muzellec", email = "boris.muzellec@owkin.com" },
]
authors = [
  { name = "Boris Muzellec" },
  { name = "Maria Telenczuk" },
  { name = "Vincent Cabelli" },
  { name = "Mathieu Andreux" },
]
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = [ "version" ]
dependencies = [
  "anndata>=0.11",
  "formulaic>=1.0.2",
  "formulaic-contrasts>=0.2",
  "matplotlib>=3.10",
  "numpy>=2.2",
  "pandas>=2.3",
  "scikit-learn>=1.6",
  "scipy>=1.15",
  "session-info2",
]
# https://docs.pypi.org/project_metadata/#project-urls
urls.Documentation = "https://pydeseq2.readthedocs.io/"
urls.Homepage = "https://github.com/scverse/PyDESeq2"
urls.Source = "https://github.com/scverse/PyDESeq2"

[dependency-groups]
dev = [
  "prek",
  "twine>=4.0.2",
]
test = [
  "coverage>=7.10",
  "pytest>=8.4",
  "pytest-cov",     # For VS Code's coverage functionality
]
doc = [
  "docutils>=0.8,!=0.18.*,!=0.19.*",
  "gitpython>=3.1.42",
  "ipython",
  "jupyter",
  "myst-parser",
  "numpydoc",
  "scanpydoc>=0.15",
  "sphinx>=8",
  "sphinx-autobuild",
  "sphinx-autodoc-typehints",
  "sphinx-book-theme>=1",
  "sphinx-click",
  "sphinx-copybutton",
  "sphinx-design",
  "sphinx-gallery",
  "sphinxcontrib-bibtex",
  "sphinxcontrib-googleanalytics>=0.5",
  "sphinxext-opengraph",
  "texttable",
]
typecheck = [
  "mypy",
  "pandas-stubs",
  "scipy-stubs",
]

[tool.hatch]
version.source = "vcs"
build.targets.wheel.packages = [ "src/pydeseq2" ]
envs.default.installer = "uv"
envs.default.dependency-groups = [ "dev" ]
envs.docs.scripts.build = "sphinx-build -M html docs docs/_build -W {args}"
envs.docs.scripts.clean = "git clean -fdX -- {args:docs}"
envs.docs.scripts.open = "python -m webbrowser -t docs/_build/html/index.html"
envs.docs.dependency-groups = [ "doc" ]
envs.hatch-test.matrix = [
  # Test the lowest and highest supported Python versions with normal deps
  { deps = [ "stable" ], python = [ "3.12", "3.14" ] },
  # Test the newest supported Python version also with pre-release deps
  { deps = [ "pre" ], python = [ "3.14" ] },
]
# If the matrix variable `deps` is set to "pre",
# set the environment variable `UV_PRERELEASE` to "allow".
envs.hatch-test.overrides.matrix.deps.env-vars = [
  { value = "allow", key = "UV_PRERELEASE", if = [ "pre" ] },
]
envs.hatch-test.dependency-groups = [ "dev", "test" ]
envs.hatch-check-types.scripts.check = [ "mypy src/pydeseq2 --ignore-missing-imports" ]
envs.hatch-check-types.dependency-groups = [ "typecheck", "test" ]

[tool.ruff]
line-length = 89
src = [ "src" ]
extend-include = [ "*.ipynb" ]
format.docstring-code-format = true
lint.select = [
  "B",      # flake8-bugbear
  "BLE",    # flake8-blind-except
  "C4",     # flake8-comprehensions
  "D",      # pydocstyle
  "E",      # Error detected by Pycodestyle
  "F",      # Errors detected by Pyflakes
  "I",      # isort
  "RUF100", # Report unused noqa directives
  "TID",    # flake8-tidy-imports
  "UP",     # pyupgrade
  "W",      # Warning detected by Pycodestyle
]
lint.ignore = [
  "D100", # Missing docstring in public module
  "D104", # Missing docstring in public package
  "D107", # Missing docstring in __init__
  # Disable one in each pair of mutually incompatible rules
  "D203", # We don't want a blank line before a class docstring
  "D213", # We want docstrings to start immediately after the opening triple quote
  "E501", # Line too long
]
lint.per-file-ignores."*/__init__.py" = [ "F401" ]
lint.per-file-ignores."docs/*" = [ "I" ]
# Ignore errors linked to sphinx gallery syntax
lint.per-file-ignores."examples/*" = [ "B018", "D205", "D400" ]
lint.per-file-ignores."tests/*" = [ "D" ]
lint.isort.force-single-line = true
lint.pydocstyle.convention = "numpy"

[tool.pytest]
ini_options.testpaths = [ "tests" ]
ini_options.addopts = [
  "--import-mode=importlib", # allow using test files with same name
]
ini_options.filterwarnings = [
  "error",
  'ignore:\s*A value is trying to be set on a copy of a DataFrame:FutureWarning',
  # ignore Pyarrow deprecation warnings
  'ignore:\s*Pyarrow will become a required dependency of pandas:DeprecationWarning',
  'ignore:\s*Setting an item of incompatible dtype:FutureWarning',
]

[tool.coverage]
run.omit = [
  "**/test_*.py",
]
run.patch = [ "subprocess" ]
run.source = [ "pydeseq2" ]

[tool.cruft]
skip = [
  ".git",
  "docs",
  "examples",
  "src",
  "tests",
]
